---
sudo: required
language: python
cache: pip
dist: trusty
group: deprecated-2017Q4
branches:
  only:
    - master
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install:
  - pip install molecule docker
script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
