---
- name: Create Splunk group
  ansible.builtin.group:
    name: "{{ splunk_forwarder_group }}"
    gid: "{{ splunk_forwarder_gid }}"
    state: present
  tags: splunk_user

- name: Create Splunk user
  ansible.builtin.user:
    name: "{{ splunk_forwarder_user }}"
    group: "{{ splunk_forwarder_group }}"
    uid: "{{ splunk_forwarder_uid }}"
    state: present
  tags: splunk_user

- name: Install Splunk on Debian X86 Based Systems
  ansible.builtin.include_tasks: install_debian.yml
  when: ansible_os_family == "Debian" and ansible_architecture != "aarch64"

- name: Install Splunk on Linux Based Arm Based Systems
  ansible.builtin.include_tasks: install_linux_aarch64.yml
  when: ansible_system == "Linux" and ansible_architecture == "aarch64"

- name: Install Splunk on Enterprise Linux Based Systems
  ansible.builtin.include_tasks: install_redhat.yml
  when: ansible_os_family == "RedHat" and ansible_architecture != "aarch64"

- name: Copy user seeds file
  ansible.builtin.template:
    src: user-seed.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_admin_user is defined and splunk_forwarder_admin_pass is defined
  tags: config_copy

- name: Copy deploymentclient file
  ansible.builtin.template:
    src: deploymentclient.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_depl_server is defined
  tags: config_copy

- name: Copy inputs file
  ansible.builtin.template:
    src: inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    mode: 0664
    backup: true
  tags: config_copy

- name: Copy outputs file
  ansible.builtin.template:
    src: outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    mode: 0664
    backup: true
  tags: config_copy

- name: Set logfile permissions
  ansible.posix.acl:
    path: "{{ item }}"
    entity: "{{ splunk_forwarder_user }}"
    state: present
    etype: user
    permissions: r
    recursive: true
  become: true
  with_items: "{{ splunk_forwarder_logs }}"

- name: Upload Splunk Systemd Script
  ansible.builtin.template:
    src: splunkd.service.j2
    dest: /etc/systemd/system/splunkd.service
    owner: root
    group: root
    mode: 0644
  notify: Enable Splunk Forwarder
  when: ansible_service_mgr == 'systemd'
