---
- name: Enable Splunk Forwarder
  ansible.builtin.service:
    name: SplunkForwarder
    enabled: true
    state: started

- name: Accept Splunk License
  become_user: splunk
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk --accept-license --answer-yes --no-prompt
  # ansible.builtin.command: /opt/splunkforwarder/bin/splunk enable boot-start -user splunk -systemd-managed 1 --accept-license --answer-yes --no-prompt
  when: not splunk_installed.stat.exists

- name: Clear config for Cloning
  ansible.builtin.command: /opt/splunkforwarder/bin/splunk clone-prep-clear-config
  when: building_image
