---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu-16.04
    image: ubuntu:16.04
    privileged: true
    command: /sbin/init
  - name: centos-7
    image: centos:7
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ./tests
