---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    service_name: splunkd.service
  vars_files:
    - "../../defaults/main.yml"
  tasks:
    - name: Get the Groups
      ansible.builtin.getent:
        database: group

    - name: Get the Users
      ansible.builtin.getent:
        database: passwd

    - name: Assert Results
      ansible.builtin.assert:
        that:
          - getent_passwd.splunkfwd is defined
          - getent_group.splunkfwd is defined
        quiet: true

    - name: Verify inputs.conf
      ansible.builtin.shell: |
        set -o pipefail
        grep 'bz2' /opt/splunkforwarder/etc/system/local/inputs.conf
      args:
        executable: /bin/bash
      register: config_settings
      failed_when: config_settings.rc != 0
      changed_when: config_settings.rc != 0

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Print service facts
      ansible.builtin.debug:
        var: ansible_facts.services["{{ service_name }}"]

    - name: Assert splunkforwarder is running
      ansible.builtin.assert:
        that: ansible_facts.services["{{ service_name }}"]["state"] == "running"
